
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.notebookmobile.code_analysis;

/** CUP generated class containing symbol constants. */
public class CodeSym {
  /* terminals */
  public static final int INT_KEYWORD = 4;
  public static final int error = 1;
  public static final int NUMBER = 3;
  public static final int IDENTIFIER = 2;
  public static final int EOF = 0;
  public static final int ASSIGN = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "NUMBER",
  "INT_KEYWORD",
  "ASSIGN"
  };
}

