
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.notebookmobile.code_analysis;

import java_cup.runtime.*;
import java.util.*;
import com.example.notebookmobile.code_analysis.instructions.*;
import com.example.notebookmobile.code_analysis.expressions.*;
import com.example.notebookmobile.code_analysis.utils.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class CodeParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public CodeParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public CodeParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CodeParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\030\000\002\002\004\000\002\002\003\000\002\003" +
    "\003\000\002\003\004\000\002\013\003\000\002\013\003" +
    "\000\002\013\003\000\002\012\005\000\002\006\006\000" +
    "\002\007\012\000\002\010\006\000\002\005\003\000\002" +
    "\005\003\000\002\004\005\000\002\004\005\000\002\004" +
    "\005\000\002\004\005\000\002\004\005\000\002\004\005" +
    "\000\002\004\004\000\002\004\004\000\002\004\003\000" +
    "\002\004\003\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\056\000\010\014\013\015\010\021\012\001\002\000" +
    "\012\002\ufffd\014\ufffd\015\ufffd\021\ufffd\001\002\000\012" +
    "\002\uffff\014\013\015\010\021\012\001\002\000\012\002" +
    "\ufffb\014\ufffb\015\ufffb\021\ufffb\001\002\000\004\002\000" +
    "\001\002\000\004\011\051\001\002\000\012\002\ufffc\014" +
    "\ufffc\015\ufffc\021\ufffc\001\002\000\004\013\047\001\002" +
    "\000\004\011\016\001\002\000\004\002\015\001\002\000" +
    "\004\002\001\001\002\000\020\004\021\005\017\011\027" +
    "\021\022\022\024\023\020\024\025\001\002\000\016\004" +
    "\021\005\017\011\027\021\022\023\020\024\025\001\002" +
    "\000\030\002\uffec\004\uffec\005\uffec\006\uffec\007\uffec\010" +
    "\uffec\012\uffec\014\uffec\015\uffec\020\uffec\021\uffec\001\002" +
    "\000\016\004\021\005\017\011\027\021\022\023\020\024" +
    "\025\001\002\000\030\002\uffea\004\uffea\005\uffea\006\uffea" +
    "\007\uffea\010\uffea\012\uffea\014\uffea\015\uffea\020\uffea\021" +
    "\uffea\001\002\000\004\012\044\001\002\000\004\012\ufff5" +
    "\001\002\000\030\002\uffeb\004\uffeb\005\uffeb\006\uffeb\007" +
    "\uffeb\010\uffeb\012\uffeb\014\uffeb\015\uffeb\020\uffeb\021\uffeb" +
    "\001\002\000\016\004\032\005\034\006\036\007\033\010" +
    "\035\012\ufff6\001\002\000\016\004\021\005\017\011\027" +
    "\021\022\023\020\024\025\001\002\000\016\004\032\005" +
    "\034\006\036\007\033\010\035\012\031\001\002\000\030" +
    "\002\uffef\004\uffef\005\uffef\006\uffef\007\uffef\010\uffef\012" +
    "\uffef\014\uffef\015\uffef\020\uffef\021\uffef\001\002\000\016" +
    "\004\021\005\017\011\027\021\022\023\020\024\025\001" +
    "\002\000\016\004\021\005\017\011\027\021\022\023\020" +
    "\024\025\001\002\000\016\004\021\005\017\011\027\021" +
    "\022\023\020\024\025\001\002\000\016\004\021\005\017" +
    "\011\027\021\022\023\020\024\025\001\002\000\016\004" +
    "\021\005\017\011\027\021\022\023\020\024\025\001\002" +
    "\000\030\002\ufff1\004\ufff1\005\ufff1\006\ufff1\007\033\010" +
    "\ufff1\012\ufff1\014\ufff1\015\ufff1\020\ufff1\021\ufff1\001\002" +
    "\000\030\002\ufff2\004\ufff2\005\ufff2\006\ufff2\007\033\010" +
    "\ufff2\012\ufff2\014\ufff2\015\ufff2\020\ufff2\021\ufff2\001\002" +
    "\000\030\002\ufff3\004\ufff3\005\ufff3\006\036\007\033\010" +
    "\035\012\ufff3\014\ufff3\015\ufff3\020\ufff3\021\ufff3\001\002" +
    "\000\030\002\ufff0\004\ufff0\005\ufff0\006\ufff0\007\ufff0\010" +
    "\ufff0\012\ufff0\014\ufff0\015\ufff0\020\ufff0\021\ufff0\001\002" +
    "\000\030\002\ufff4\004\ufff4\005\ufff4\006\036\007\033\010" +
    "\035\012\ufff4\014\ufff4\015\ufff4\020\ufff4\021\ufff4\001\002" +
    "\000\012\002\ufff9\014\ufff9\015\ufff9\021\ufff9\001\002\000" +
    "\030\002\uffee\004\uffee\005\uffee\006\uffee\007\uffee\010\uffee" +
    "\012\uffee\014\uffee\015\uffee\020\uffee\021\uffee\001\002\000" +
    "\030\002\uffed\004\uffed\005\uffed\006\036\007\033\010\035" +
    "\012\uffed\014\uffed\015\uffed\020\uffed\021\uffed\001\002\000" +
    "\016\004\021\005\017\011\027\021\022\023\020\024\025" +
    "\001\002\000\024\002\ufffa\004\032\005\034\006\036\007" +
    "\033\010\035\014\ufffa\015\ufffa\021\ufffa\001\002\000\016" +
    "\004\021\005\017\011\027\021\022\023\020\024\025\001" +
    "\002\000\016\004\032\005\034\006\036\007\033\010\035" +
    "\020\053\001\002\000\016\004\021\005\017\011\027\021" +
    "\022\023\020\024\025\001\002\000\016\004\032\005\034" +
    "\006\036\007\033\010\035\020\055\001\002\000\016\004" +
    "\021\005\017\011\027\021\022\023\020\024\025\001\002" +
    "\000\016\004\032\005\034\006\036\007\033\010\035\012" +
    "\057\001\002\000\012\002\ufff8\014\ufff8\015\ufff8\021\ufff8" +
    "\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\056\000\016\002\013\003\006\006\010\007\005\012" +
    "\003\013\004\001\001\000\002\001\001\000\014\003\057" +
    "\006\010\007\005\012\003\013\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\025\005\022\001\001\000\004" +
    "\004\045\001\001\000\002\001\001\000\004\004\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\004\027\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\004\042" +
    "\001\001\000\004\004\041\001\001\000\004\004\040\001" +
    "\001\000\004\004\037\001\001\000\004\004\036\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\004\047\001\001\000" +
    "\002\001\001\000\004\004\051\001\001\000\002\001\001" +
    "\000\004\004\053\001\001\000\002\001\001\000\004\004" +
    "\055\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CodeParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CodeParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CodeParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Fields
    CodeLexer lex;
    private List<String> syntaxErrors;
    private Analyzer analyzer;

    // Connect the parser with the lexer
    public CodeParser(CodeLexer lex, Analyzer analyzer){
        super(lex);
        this.analyzer = analyzer;
        syntaxErrors = new LinkedList<>();
    }

    // Getters
    public CodeLexer getLexer(){
        return this.lex;
    }
    public List<String> getSyntaxErrors(){
        return this.syntaxErrors;
    }

    /* Overwrite error methods */
    public void syntax_error(Symbol cur_token) {
        StringBuilder mssBuilder = new StringBuilder("Simbolo: ");
        mssBuilder.append(symbl_name_from_id(cur_token.sym));

        if(cur_token.value != null){
            mssBuilder.append(", lexema <");
            mssBuilder.append(cur_token.value.toString());
            mssBuilder.append(">");
        }
        mssBuilder.append(", linea: ");
        mssBuilder.append(cur_token.left);
        mssBuilder.append(", columna: ");
        mssBuilder.append(cur_token.right);

        if (expected_token_ids().isEmpty()) {
            mssBuilder.append(" -- ya no se esperaba ningun simbolo");
        } else {
            mssBuilder.append(" -- Se esperaba [");
            for (Integer expected_token_id : expected_token_ids()) {
                if(!symbl_name_from_id(expected_token_id).equals("error")){
                    mssBuilder.append(symbl_name_from_id(expected_token_id));
                    mssBuilder.append(" ");
                }

            }
            mssBuilder.append("]");
        }
        syntaxErrors.add(mssBuilder.toString());
    }

    public void report_error(String message, Object info){
        try{
            Symbol cur_token = (Symbol) info;
            StringBuilder mssBuilder = new StringBuilder("Simbolo: ");
            mssBuilder.append(symbl_name_from_id(cur_token.sym));
            mssBuilder.append(", linea: ");
            mssBuilder.append(cur_token.left);
            mssBuilder.append(", columna: ");
            mssBuilder.append(cur_token.right);
            if(cur_token != null){
                mssBuilder.append(", Lexema: ");
                mssBuilder.append(cur_token.value);
            }

            if(message != null){
                mssBuilder.append(", Info: ");
                mssBuilder.append(message);
            }

            syntaxErrors.add(mssBuilder.toString());
        } catch (Exception e){
            syntaxErrors.add(message);
        }
    }


    public void unrecovered_syntax_error(Symbol cur_token) {
        syntaxErrors.add("Errores de sintaxis severos detectados, revisa municiosamente el codigo");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$CodeParser$actions {
  private final CodeParser parser;

  /** Constructor */
  CUP$CodeParser$actions(CodeParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$CodeParser$do_action_part00000000(
    int                        CUP$CodeParser$act_num,
    java_cup.runtime.lr_parser CUP$CodeParser$parser,
    java.util.Stack            CUP$CodeParser$stack,
    int                        CUP$CodeParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CodeParser$result;

      /* select the action based on the action number */
      switch (CUP$CodeParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= s EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		RESULT = start_val;
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$CodeParser$parser.done_parsing();
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // s ::= instructions 
            {
              Object RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		List<Instruction> list = (List<Instruction>)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		

            analyzer.execute(list);
        
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // instructions ::= instruction 
            {
              List<Instruction> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Instruction i = (Instruction)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
            List<Instruction> list = new LinkedList<Instruction>();
            list.add(i);
            RESULT = list;
        
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("instructions",1, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // instructions ::= instruction instructions 
            {
              List<Instruction> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Instruction i = (Instruction)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		List<Instruction> l = (List<Instruction>)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
            l.add(0, i);
            RESULT = l;
        
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("instructions",1, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruction ::= assignation 
            {
              Instruction RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Instruction i = (Instruction)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		 RESULT = i; 
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruction ::= print_function 
            {
              Instruction RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Instruction i = (Instruction)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		 RESULT = i; 
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruction ::= plot_function 
            {
              Instruction RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Instruction i = (Instruction)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		 RESULT = i; 
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // assignation ::= ID EQUALS operable 
            {
              Instruction RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
            RESULT = new Assignation(i, e, new Position(ileft, iright));
        
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("assignation",8, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // print_function ::= PRINT LPAREN expression RPAREN 
            {
              Instruction RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		
            RESULT = new PrintFunction(e, new Position(pleft, pright));
        
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("print_function",4, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // plot_function ::= PLOT LPAREN operable COMMA operable COMMA operable RPAREN 
            {
              Instruction RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-7)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-7)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-7)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-5)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-5)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		
            //TODO
        
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("plot_function",5, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-7)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // format_function ::= FORMAT LPAREN operable RPAREN 
            {
              Instruction RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Expression s = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		
            //TODO
        
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("format_function",6, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-3)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expression ::= operable 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		 RESULT = e; 
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("expression",3, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expression ::= STRING_LIT 
            {
              Expression RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		 RESULT = new Literal(l); 
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("expression",3, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // operable ::= operable PLUS operable 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
                RESULT = new Operation(
                    DefineOperation.PLUS,
                    e1, e2,
                    new Position(oleft, oright)
                );
            
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // operable ::= operable MINUS operable 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
                RESULT = new Operation(
                    DefineOperation.MINUS,
                    e1, e2,
                    new Position(oleft, oright)
                );
            
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // operable ::= operable DIV operable 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
                RESULT = new Operation(
                    DefineOperation.DIV,
                    e1, e2,
                    new Position(oleft, oright)
                );
            
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // operable ::= operable TIMES operable 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
                RESULT = new Operation(
                    DefineOperation.TIMES,
                    e1, e2,
                    new Position(oleft, oright)
                );
            
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // operable ::= operable POWER operable 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
                RESULT = new Operation(
                    DefineOperation.POWER,
                    e1, e2,
                    new Position(oleft, oright)
                );
            
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // operable ::= LPAREN operable RPAREN 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		 RESULT = e; 
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-2)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // operable ::= PLUS operable 
            {
              Expression RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
                RESULT = new UnaryOperation(
                    DefineOperation.PLUS, e, new Position(oleft, oright)
                );
            
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // operable ::= MINUS operable 
            {
              Expression RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
                RESULT = new UnaryOperation(
                    DefineOperation.MINUS, e, new Position(oleft, oright)
                );
            
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.elementAt(CUP$CodeParser$top-1)), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // operable ::= INTEGER_LIT 
            {
              Expression RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Float l = (Float)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		 RESULT = new Literal(l); 
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // operable ::= FLOAT_LIT 
            {
              Expression RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		Float l = (Float)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		 RESULT = new Literal(l); 
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // operable ::= ID 
            {
              Expression RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$CodeParser$stack.peek()).value;
		
                RESULT = new VariableAccess(i, new Position(ileft, iright)) ;
            
              CUP$CodeParser$result = parser.getSymbolFactory().newSymbol("operable",2, ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodeParser$stack.peek()), RESULT);
            }
          return CUP$CodeParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$CodeParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$CodeParser$do_action(
    int                        CUP$CodeParser$act_num,
    java_cup.runtime.lr_parser CUP$CodeParser$parser,
    java.util.Stack            CUP$CodeParser$stack,
    int                        CUP$CodeParser$top)
    throws java.lang.Exception
    {
              return CUP$CodeParser$do_action_part00000000(
                               CUP$CodeParser$act_num,
                               CUP$CodeParser$parser,
                               CUP$CodeParser$stack,
                               CUP$CodeParser$top);
    }
}

}
