
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.notebookmobile.code_analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int PLOT = 11;
  public static final int STRING_LIT = 15;
  public static final int PLUS = 2;
  public static final int RPAREN = 8;
  public static final int LPAREN = 7;
  public static final int ID = 14;
  public static final int EQUALS = 9;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int INTEGER_LIT = 16;
  public static final int MINUS = 3;
  public static final int PRINT = 10;
  public static final int error = 1;
  public static final int FORMAT = 12;
  public static final int FLOAT_LIT = 17;
  public static final int POWER = 5;
  public static final int UMINUS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "POWER",
  "DIV",
  "LPAREN",
  "RPAREN",
  "EQUALS",
  "PRINT",
  "PLOT",
  "FORMAT",
  "UMINUS",
  "ID",
  "STRING_LIT",
  "INTEGER_LIT",
  "FLOAT_LIT"
  };
}

